coma/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('course/', include('course.urls')),
    path('student/', include('student.urls')),
]


if settings.DEBUG : # if we are in development env,
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

course/urls.py
from django.urls import path


from .views import (
    renderCourseDetailsView,
    renderCourseMaterialsView,
    renderAssignmentView,
    renderPracticalView,
    renderAttendanceView,
    renderAttendanceDetailsView,
    renderAssignmentSubmitView,
    renderPracticalSubmitView,
    renderFeedbacksView,
    renderFeedbackSubmitView,
    renderAnnouncementsView,
    renderCourseUpdatesView,
)


urlpatterns = [
    path('<str:course_id>/details', renderCourseDetailsView, name='details'),
    
    
    path('<str:course_id>/materials', renderCourseMaterialsView, name='materials'),
    # rather than course/materials/1 can we use course/1/materials ????
    path('<str:course_id>/assignments', renderAssignmentView, name='assignments'),
    path('<str:course_id>/practicals', renderPracticalView, name='practicals'),
    path('<str:course_id>/attendance', renderAttendanceView, name='attendance'),
    path('<str:course_id>/feedbacks', renderFeedbacksView, name='feedbacks'),
    path('<str:course_id>/announcements', renderAnnouncementsView, name='announcements'),
    path('<str:course_id>/course-updates', renderCourseUpdatesView, name='course-updates'),
    
    path('attendance-details/<str:attendance_id>', renderAttendanceDetailsView, name='attendance-details'),
    
    
    path('submit-assignment/<str:assignment_id>', renderAssignmentSubmitView, name='submit-assignment'),
    path('submit-practical/<str:practical_id>', renderPracticalSubmitView, name='submit-practical'),
    path('<str:course_id>submit-feedback', renderFeedbackSubmitView, name='submit-feedback'),
]

course/models.py
import datetime
import os
import pandas as pd

from django.db import models
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

from django.utils import timezone


from personal.models import (
    Course,
    EmailRecord,
    Faculty,
)

from student.models import (
    AttendanceDetails,
    Student,
    AssignmentSubmission,
    PracticalSubmission,
)

# Create your models here.

MATERIAL_TYPE = (
    ('Link', 'Link'),
    ('File', 'File'),
)

ASSIGNMENT_TYPE = (
    ('Theory', 'Theory'),
    ('Lab', 'Lab'),
)

PRACTICAL_TYPE = (
    ('Offline', 'Offline'),
    ('Online', 'Online'),
)

RATING = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
)

REMARK = (
    ('Excellent', 'Excellent'),
    ('Very Good', 'Very Good'),
    ('Good', 'Good'),
    ('Fair', 'Fair'),
    ('Poor', 'Poor'),
    ('Very Poor', 'Very Poor'),
)



def custom_upload_to_materials(instance, filename) :
    return os.path.join(instance.course.course_code + '/materials/' + filename)

def custom_upload_to_assignments(instance, filename) :
    return os.path.join(instance.course.course_code + '/assignments/' + filename)

def custom_upload_to_practicals(instance, filename) :
    return os.path.join(instance.course.course_code + '/practicals/' + filename)

def custom_upload_to_attendance(instance, filename) :
    return os.path.join(instance.course.course_code + '/attendance/' + filename)



class CourseMaterial(models.Model) :
    material_name = models.CharField(max_length=255, blank=False)
    
    material_type = models.CharField(max_length=255, null=False, choices=MATERIAL_TYPE)

    material_link = models.CharField(max_length=255, blank=True)

    material_file = models.FileField(max_length=255, blank=True, upload_to=custom_upload_to_materials)

    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)


    def __str__(self) :
        return 'material for ' + self.course.course_name + ' (' + str(self.id) +')'

    def save(self, *args, **kwargs) :
        try :
            instructor = self.course.teacher.name
        except Exception as e :
            instructor = None
        course = self.course.course_name

        # students = Student.objects.all()

        email_records = self.course.emailrecord_set.all()
        for email_record in email_records :
            print("trying ", email_record)
            try :
                if email_record.student :
                    name = email_record.name

                    email_body = render_to_string('course/material_mail.html', {'name': name, 'instructor': instructor, 'course': course})
                    recipient = email_record.email

                    email = EmailMessage(
                        'New Material',
                        email_body,
                        settings.EMAIL_HOST_USER,
                        [recipient],
                    )

                    email.send()

                    print(f"mail sent to {email_record.email}")
            except Student.DoesNotExist :
                print("student is not registered")

            super().save(*args, **kwargs)


class Assignment(models.Model) :
    assignment_name = models.CharField(max_length=255, blank=False)

    assignment_type = models.CharField(max_length=255, null=False, choices=ASSIGNMENT_TYPE)

    questions_link = models.CharField(max_length=255, blank=True)

    questions_file = models.FileField(max_length=255, blank=True, upload_to=custom_upload_to_assignments)

    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)
    
    deadline = models.DateTimeField(blank=False)

    def __str__(self) :
        return 'assignment for ' + self.course.course_name + ' (' + str(self.id) + ')'


    def save(self, *args, **kwargs) :
        try :
            instructor = self.course.teacher.name
        except Exception as e :
            instructor = None
        course = self.course.course_name

        super().save(*args, **kwargs)

        # students = Student.objects.all()

        email_records = self.course.emailrecord_set.all()
        for email_record in email_records :
            print("trying ", email_record)
            try :
                if email_record.student :
                    # first create an AssignmentSubmission object,
                    assignment_submission = AssignmentSubmission.objects.create(
                        student=email_record.student,
                        assignment=self,
                    )

                    name = email_record.name

                    email_body = render_to_string('course/assignment_mail.html', {'name': name, 'instructor': instructor, 'course': course})
                    recipient = email_record.email

                    email = EmailMessage(
                        'New Assignment',
                        email_body,
                        settings.EMAIL_HOST_USER,
                        [recipient],
                    )

                    email.send()

                    print(f"mail sent to {email_record.email}")
            except Student.DoesNotExist :
                print("student is not registered")

        # super().save(*args, **kwargs)


class Practical(models.Model) :
    practical_name = models.CharField(max_length=255, blank=False)

    practical_type = models.CharField(max_length=255, null=False, choices=PRACTICAL_TYPE)

    questions_link = models.CharField(max_length=255, blank=True)

    questions_file = models.FileField(max_length=255, blank=True, upload_to=custom_upload_to_practicals)

    lab_room_no = models.CharField(max_length=255, blank=True)

    instructor = models.ForeignKey(Faculty, null=True, on_delete=models.SET_NULL)

    time = models.DateTimeField(blank=False)

    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)

    def __str__(self) :
        return 'practical for ' + self.course.course_name + ' (' + str(self.id) + ')'


    def save(self, *args, **kwargs) :
        try :
            instructor = self.instructor.name
        except Exception as e :
            instructor = None
        course = self.course.course_name

        super().save(*args, **kwargs)


        # students = Student.objects.all()

        # email_records enrolled in this course,
        email_records = self.course.emailrecord_set.all()
        for email_record in email_records :
            print("trying ", email_record)
            try :
                if email_record.student :
                    # student = email_record.student

                    practical_submission = PracticalSubmission.objects.create(
                        student=email_record.student,
                        practical=self,
                    )

                    name = email_record.name

                    email_body = render_to_string('course/practical_email.html', {'name': name, 'instructor': instructor, 'course': course})
                    recipient = email_record.email

                    email = EmailMessage(
                        'New Practical',
                        email_body,
                        settings.EMAIL_HOST_USER,
                        [recipient],
                    )

                    email.send()
                    
                    print(f"mail sent to {email_record.email}")
            except Student.DoesNotExist :
                print("student is not registered")



class DailyAttendance(models.Model) :
    attendance_sheet = models.FileField(max_length=255, upload_to=custom_upload_to_attendance)

    date = models.DateTimeField(blank=False, auto_now_add=True)

    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)

    def __str__(self) :
        if not self.course :
            return f"course is deleted, id({self.id})"
        return 'attendance for ' + self.course.course_name + ' (' + str(self.date) + ')'


    def save(self, *args, **kwargs) :

        super().save(*args, **kwargs)

        file_path = settings.MEDIA_ROOT + '/' + self.attendance_sheet.name

        attendance_df = pd.read_excel(file_path)

        print(attendance_df.head())
        print(f"columns {attendance_df.columns}")

        enrollment_numbers = attendance_df['Enrollment Number']
        attendance = attendance_df['Attendance']

        for enrollment_number, present  in zip(enrollment_numbers, attendance) :
            print(f"for {enrollment_number}")
            try :
                email_record = EmailRecord.objects.get(enrollment_no__iexact=enrollment_number)

                try :
                    student = Student.objects.get(email_record=email_record)

                    try :
                        attendance_details = AttendanceDetails.objects.get(student=student, course=self.course)

                        attendance_details.total_classes += 1

                        if present.lower() == 'yes' :
                            attendance_details.total_presents += 1

                        if present.lower() == 'no' :
                            attendance_details.total_absents += 1

                        attendance_details.save()

                    except AttendanceDetails.DoesNotExist :
                        print("AttendanceDetails object does not exist")

                except Student.DoesNotExist :
                    print('Student does not exist')

            except EmailRecord.DoesNotExist :
                print('Email record does not exist')



class Question(models.Model) :
    question = models.CharField(max_length=255, blank=False)

    def __str__(self) :
        return self.question




class Feedback(models.Model) :
    student = models.ForeignKey(Student, null=True, on_delete=models.SET_NULL)
    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)

    rate = models.IntegerField(null=False, choices=RATING)
    review = models.TextField(blank=True)

    def __str__(self) :

course/forms.py
from django import forms

from .models import (
    Feedback,
    RATING,
    REMARK,

    AssignmentSubmission,
)


class AssignmentSubmissionForm(forms.Form) :
    answer_file = forms.FileField(required=True)

class PracticalSubmissionForm(forms.Form) :
    file = forms.FileField(required=True)

class FeedbackForm(forms.ModelForm) :
    how_would_you_rate_the_course = forms.IntegerField(widget=forms.RadioSelect(choices=RATING))
    # course_content_was = forms.CharField(widget=forms.RadioSelect(choices=REMARK))
    # explanations_by_instructor_were = forms.CharField(widget=forms.RadioSelect(choices=REMARK))
    # availability_of_extra_help_when_needed_was = forms.CharField(widget=forms.RadioSelect(choices=REMARK))
    # grading_techniques_were = forms.CharField(widget=forms.RadioSelect(choices=REMARK))
    # the_amount_of_effort_you_put_into_this_course_was = forms.CharField(widget=forms.RadioSelect(choices=REMARK))
    class Meta :
        model = Feedback
        fields = (
            'how_would_you_rate_the_course',
            # 'course_content_was',
            # 'explanations_by_instructor_were',
            # 'availability_of_extra_help_when_needed_was',
            # 'grading_techniques_were',
            # 'the_amount_of_effort_you_put_into_this_course_was',
            'review'
        )

templates/course/announcements.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}

    <div class="announcements-div">
        {% for announcement in announcements %}
            <div class="announcement-card">
                <div class="announcement-date">{{announcement.date}}</div>
                <div class="announcement-content">
                    <p>{{announcement.content}}</p>
                </div>
            </div>
        {% endfor %}
    </div>


{% endblock %}

templates/course/assignment_mail.html
{% autoescape off %}

Dear {{name}},

{{instructor}} has added a new assignment for the course {{course}}.


{% endautoescape %}

templates/course/assignment_submit.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}

    <form action="" method="post" enctype="multipart/form-data" class="assignment-submit-form">
        {% csrf_token %}
        <table class="assignment-submit-table">
            <tr class="table-row">
                <th>
                    <label for="id_answer_file">Answer File:</label>
                </th>
                <td>
                    <input type="file" name="answer_file" required id="id_answer_file">
                </td>
            </tr>
            <tr><td><br></td></tr>
        </table>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

templates/course/attendance_details.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}
    <table class="attendance-table">
        <tr class="head-row">
            <th>Index</th>
            {% for column in columns %}
                <th>{{column}}</th>
            {% endfor %}
        </tr>

        {% for ind, name, enrollment_no, attendance in attendance_table %}
            <tr>
                <td class="index-column">{{ind}}</td>
                <td class="name-column">{{name}}</td>
                <td class="enrollment-column">{{enrollment_no}}</td>
                <td class="attendance-column">{{attendance}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/course/attendances.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}

    <div class="student-attendance-details">
        {% if request.user.is_authenticated %}
            <div class="attendance-stats">
                <div class="total-classes flex-center">
                    <h5>Classes taken</h5>
                    <span class="stat-number">{{total_classes}}</span>
                </div>
                <div class="total-presents flex-center">
                    <h5>Classes attended</h5>
                    <span class="stat-number">{{total_presents}}</span>
                </div>
                <div class="total-absents flex-center">
                    <h5>Classes not attended</h5>
                    <span class="stat-number">{{total_absents}}</span>
                </div>
            </div>
        {% else %}
            <div class="attendance-login">
                <p>log in to view your attendance details for this course</p>
            </div>
        {% endif %}
    </div>

    <div class="attendance-div">
        <span class="click-to-view">Click to view detailed attendance</span>
        {% for course_attendance in course_attendances %}
            <div class="attendance-item">
                <a href="{% url 'attendance-details' course_attendance.id %}" target="_blank">
                    Attendance for {{course_attendance.course}} on {{course_attendance.date}}
                </a>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/course/course_details.html
{% extends 'course/course_head.html' %}
{% load static %}

templates/course/course_head.html
{% extends 'personal/main.html' %}
{% load static %}


{% block content %}

    <div class="course-page-head">
        <!-- course is {{course.id}} -->
        <div class="course-head-item">
            <a href="{% url 'materials' course.id %}" class="materials-link">Materials</a>
        </div>
        <div class="course-head-item">
            <a href="{% url 'practicals' course.id %}" class="practicals-link">Practicals</a>
        </div>
        <div class="course-head-item">
            <a href="{% url 'assignments' course.id %}" class="assignments-link">Assignments</a>
        </div>

        <div class="course-head-item">
            <a href="{% url 'attendance' course.id %}" class="attendance-link">Attendance</a>
        </div>

        <div class="course-head-item">
            <a href="{% url 'feedbacks' course.id %}" class="feedback-link">Feedbacks</a>
        </div>

        <div class="course-head-item">
            <a href="{% url 'announcements' course.id %}" class="announcement-link">Announcements</a>
        </div>

        <div class="course-head-item">
            <a href="{% url 'course-updates' course.id %}" class="update-link">Updates</a>
        </div>
    </div>

    <div class="messages">
            {% for message in messages%}
                <div class="message-card">
                    <p class="message-text"><strong>{{message}}</strong></p>
                    <div class="dismisser flex-center">
                        <i class="fas fa-square-xmark"></i>
                    </div>
                </div>
            {% endfor %}

            <script src="{% static 'js/index.js' %}"></script>
    </div>


    {% block course_body %}


    {% endblock %}

{% endblock %}

templates/course/feedback_submit.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}

    <form action="" method="post" enctype="multipart/form-data" class="assignment-submit-form">
        {% csrf_token %}
        <table class="assignment-submit-table feedback-submit-table">

            {% for question in questions %}
                <tr>
                    <th><label name="questions" for="answers">{{question.question}}</label></th>
                    <td>
                        <textarea name="answers" cols="40" rows="2" id="answers"></textarea>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <th><label>How would you rate the course:</label></th>
                <td>
                
                    <div id="id_how_would_you_rate_the_course">
                        <div>
                            <label for="id_how_would_you_rate_the_course_0"><input type="radio" name="how_would_you_rate_the_course"
                                    value="1" required id="id_how_would_you_rate_the_course_0">
                                1</label>
                        </div>
                        <div>
                            <label for="id_how_would_you_rate_the_course_1"><input type="radio" name="how_would_you_rate_the_course"
                                    value="2" required id="id_how_would_you_rate_the_course_1">
                                2</label>
                        </div>
                        <div>
                            <label for="id_how_would_you_rate_the_course_2"><input type="radio" name="how_would_you_rate_the_course"
                                    value="3" required id="id_how_would_you_rate_the_course_2">
                                3</label>
                        </div>
                        <div>
                            <label for="id_how_would_you_rate_the_course_3"><input type="radio" name="how_would_you_rate_the_course"
                                    value="4" required id="id_how_would_you_rate_the_course_3">
                                4</label>
                        </div>
                        <div>
                            <label for="id_how_would_you_rate_the_course_4"><input type="radio" name="how_would_you_rate_the_course"
                                    value="5" required id="id_how_would_you_rate_the_course_4">
                                5</label>
                        </div>
                    </div>
                </td>
            </tr>
            
            <tr><td><br></td></tr>

            
            

            
            <tr>
                <th><label for="id_review">Review:</label></th>
                <td>
                    <textarea name="review" cols="40" rows="10" id="id_review"></textarea>
                </td>
            </tr>

            <tr><td><br></td></tr>
        
        </table>

        <button type="submit" class="btn btn-primary">Submit</button>

        <div class="messages">
            {% for error in errors%}
                <div class="message-card">
                    <p class="message-text"><strong>{{error}}</strong></p>
                    <div class="dismisser flex-center">
                        <i class="fas fa-square-xmark"></i>
                    </div>
                </div>
            {% endfor %}

            <script src="{% static 'js/index.js' %}"></script>
        </div>
    </form>

{% endblock %}

templates/course/feedbacks.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}

    <div class="feedbacks-stats">
        <div class="total-feedbacks flex-center">
            <h5>Total Feedbacks</h5>
            <span class="stat-number">{{total_feedbacks}}</span>
        </div>

        <div class="highest-rate flex-center">
            <h5>Highest Rating</h5>
            <span class="stat-number">{{highest_rate}}</span>
        </div>

        <div class="rate-frequencies flex-center">
            <table class="rates-table">
                <tr>
                    <td class="rate-column">Rate</td>
                    <td class="frequency-column">Frequency</td>
                </tr>
                <tr>
                    <td class="rate-column">5</td>
                    <td class="frequency-column">{{rate_5}}</td>
                </tr>
                <tr>
                    <td class="rate-column">4</td>
                    <td class="frequency-column">{{rate_4}}</td>
                </tr>
                <tr>
                    <td class="rate-column">3</td>
                    <td class="frequency-column">{{rate_3}}</td>
                </tr>
                <tr>
                    <td class="rate-column">2</td>
                    <td class="frequency-column">{{rate_2}}</td>
                </tr>
                <tr>
                    <td class="rate-column">1</td>
                    <td class="frequency-column">{{rate_1}}</td>
                </tr>
            </table>
        </div>
    </div>

    {% if request.user.is_authenticated %}
    
        <div class="feedback-submission">
            <a href="{% url 'submit-feedback' course.id %}" target="_blank">Submit your feedback for this course</a>
        </div>

    {% endif %}


    <div class="feedbacks-div">
        {% for course_feedback in course_feedbacks %}
            <div class="feedback-card">
                <div class="feedback-rate flex-center"><span>{{course_feedback.rate}}</span></div>
                <div class="feedback-review flex-center">
                    <p>{{course_feedback.review}}</p>
                </div>
            </div>
            <div class="feedback-qandas">
                {% for feedbackqanda in course_feedback.feedbackqanda_set.all %}
                <div class="feedback-question">
                    <span>Q</span>
                    <p>{{feedbackqanda.question}}?</p>
                </div>
                    <div class="feedback-answer">
                    <span>A</span>
                    <p>{{feedbackqanda.answer}}</p>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/course/material_mail.html
{% autoescape off %}

Dear {{name}},

{{instructor}} has added a new material for the course {{course}}.


{% endautoescape %}

templates/course/materials.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}

    <div class="materials-div">
        {% for course_material in course_materials %}
            <div class="material-card">
                <p>{{course_material.material_name}}</p>
                <a href="{{course_material.material_file.url}}" target="_blank" class="click-for-file">Click here for file</a>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/course/practical_email.html
{% autoescape off %}

Dear {{name}},

{{instructor}} has added a new practical for the course {{course}}.


{% endautoescape %}

templates/course/practical_submit.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}

    <form action="" method="post" enctype="multipart/form-data" class="assignment-submit-form">
        {% csrf_token %}
        <table class="assignment-submit-table">
            <tr class="table-row">
                <th>
                    <label for="id_file">File:</label>
                </th>
                <td>
                    <input type="file" name="file" required id="id_file">
                </td>
            </tr>
            <tr><td><br></td></tr>
        </table>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

templates/course/updates.html
{% extends 'course/course_head.html' %}
{% load static %}


{% block course_body %}
    <div class="updates-div">
        {% for course_update in course_updates %}
            <div class="update-card">
                <div class="update-date">{{course_update.date}}</div>
                <div class="update-content">
                    <p>{{course_update.content}}</p>
                </div>
                <div class="update-resource-link">
                    <a href="{{course_update.link}}" target="_blank">Find course details</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}