coma/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('course/', include('course.urls')),
    path('student/', include('student.urls')),
]


if settings.DEBUG : # if we are in development env,
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

student/urls.py
from django.urls import path

from .views import (
    renderRegisterView,
    renderLoginView,
    renderLogoutView,
)



urlpatterns = [
    path('register', renderRegisterView, name='register'),
    path('login', renderLoginView, name='login'),
    path('logout', renderLogoutView, name='logout'),
]

student/models.py
import os


from django.db import models

from django.contrib.auth.models import User


# from course.models import (
#     Assignment,
# )

from personal.models import (
    Course,
    EmailRecord,
)


def custom_upload_to_assignments_submissions(instance, filename) :
    return os.path.join(instance.assignment.course.course_code + '/assignments/submissions/' + instance.student.email_record.enrollment_no + ', ' + filename)

def custom_upload_to_practicals_submissions(instance, filename) :
    return os.path.join(instance.practical.course.course_code + '/practicals/submissions/' + instance.student.email_record.enrollment_no + ', ' + filename)



# Create your models here.

class Student(models.Model) :
    user = models.OneToOneField(User, null=False, on_delete=models.CASCADE)
    # if user is deleted, student is also deleted,

    # name = models.CharField(max_length=255)
    # email = models.EmailField(max_length=255, unique=True)
    # enrollment_no = models.CharField(max_length=255, unique=True)

    email_record = models.OneToOneField(EmailRecord, on_delete=models.CASCADE, default=None)
    # if email_record is deleted, student is also deleted,

    assignments = models.ManyToManyField('course.Assignment', blank=True)
    practicals = models.ManyToManyField('course.Practical', blank=True)


    def __str__(self) :
        return self.email_record.name

class AssignmentSubmission(models.Model) :
    student = models.ForeignKey(Student, null=True, on_delete=models.SET_NULL)
    assignment = models.ForeignKey('course.Assignment', null=True, on_delete=models.SET_NULL)

    answer_file = models.FileField(max_length=255, null=True, upload_to=custom_upload_to_assignments_submissions)

    date = models.DateTimeField(auto_now_add=True, null=True)

    pending = models.BooleanField(default=False)
    submitted = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    missing = models.BooleanField(default=False)

    def __str__(self) :
        if not self.student or not self.assignment :
            return "student or assignment deleted " + f"id({str(self.id)})"
        return str(self.student.email_record.name) + ', ' + str(self.assignment.assignment_name)

class PracticalSubmission(models.Model) :
    student = models.ForeignKey(Student, null=True, on_delete=models.SET_NULL)
    practical = models.ForeignKey('course.Practical', null=True, on_delete=models.SET_NULL)

    answer_file = models.FileField(max_length=255, null=True, upload_to=custom_upload_to_practicals_submissions)

    date = models.DateTimeField(auto_now_add=True, null=True)


    pending = models.BooleanField(default=False)
    submitted = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    missing = models.BooleanField(default=False)

    def __str__(self) :
        if not self.student or not self.practical :
            return "student or practical deleted " + f"id({str(self.id)})"
        return str(self.student.email_record.name) + ', ' + str(self.practical.practical_name)


class AttendanceDetails(models.Model) :
    student = models.ForeignKey(Student, null=True, on_delete=models.SET_NULL)
    # this time i used EmailRecord Model to relate AttendanceDetails and a student, rather than Student Model
    # now, we create AttendanceDetails objects when EmailRecord object is created (overriding EmailRecord.save() method)
    
    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)


    total_classes = models.IntegerField(default=0)
    total_presents = models.IntegerField(default=0)
    total_absents = models.IntegerField(default=0)


    def __str__(self) :
        if not self.student or not self.course :
            return "email record or course deleted " + f"id({str(self.id)})"
        return "AttendanceDetails for " + self.student.email_record.enrollment_no + ', ' + str(self.course.course_name)

student/forms.py
from django import forms
# from django.forms import 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import (
    Student,
)


# first create a User model object and then a Student model object,
    # then connect both of'em with OneToOne relation,

class UserRegistrationForm(UserCreationForm) :

    enrollment_no = forms.CharField(max_length=255, required=True)

    class Meta:
        model = User
        fields = ('enrollment_no', 'username', 'password1', 'password2')

student/views.py
from django.shortcuts import redirect, render

from django.contrib.auth import (
    authenticate,
    login,
    logout,
)

from .models import (
    AttendanceDetails,
    Student,
)


from personal.models import (
    EmailRecord,
)

from student.models import (
    AssignmentSubmission,
    PracticalSubmission,
)

from .forms import (
    UserRegistrationForm,
)


APP_NAME = 'student'

# Create your views here.


def renderLoginView(request) :
    if(request.user.is_authenticated) :
        return redirect('home')


    context = {}

    if request.method == 'POST' :
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None :
            login(request, user)

            print('logged in')

            return redirect('home')
        else :
            print("incorrect username or password")
            return redirect('login')
    else :
        return render(request, APP_NAME + '/login.html', context)

def renderRegisterView(request) :
    if(request.user.is_authenticated) :
        return redirect('home')

    context = {}
    
    if request.method == 'POST' :
        registerForm = UserRegistrationForm(request.POST)
        
        if registerForm.is_valid() :
            enrollment_no=request.POST['enrollment_no']

            # check if the enrollment_no is there or not,
            try :
                email_record = EmailRecord.objects.get(enrollment_no__iexact=enrollment_no)

            
            except EmailRecord.DoesNotExist :
                print("EmailRecord does not exist")
                return redirect('home')
            
            
            
            # check if an account is already registered for that enrollment_no
            try :
                students = Student.objects.get(email_record=email_record)
                print("student already registered")
                return redirect('home')
            
            except Student.DoesNotExist :
                print("student not registered")

                

            user = registerForm.save()

            student = Student.objects.create(
                user=user,

                # name and email must be retrieved from the college record of that enrollment_no,
                # name=email_record.name,
                # email=email_record.email,

                # enrollment_no=enrollment_no,
                
                email_record=email_record,
            )

            print(f"student for {student} created")


            # when a new student is registered,
                # we will create submission objects for practicals and assignments that are already posted for his courses,

            enrolled_courses = email_record.enrolled_courses.all()
            for course in enrolled_courses :
                course_practicals = course.practical_set.all()
                for practical in course_practicals :
                    practical_submission = PracticalSubmission.objects.create(
                        student=student,
                        practical=practical,
                    )

                course_assignments = course.assignment_set.all()
                for assignment in course_assignments :
                    assignment_submission = AssignmentSubmission.objects.create(
                        student=student,
                        assignment=assignment,
                    )

                
                attendance_details = AttendanceDetails.objects.create(
                    student=student,
                    course=course,
                )

            print(f"student --> {student}")

            return redirect('login')
        else :
            context['registerForm'] = registerForm
            print(f"RegisterForm Invalid")
    else :
        registerForm = UserRegistrationForm()
        context['registerForm'] = registerForm
        # print(registerForm)

    return render(request, APP_NAME + '/register.html', context)


def renderLogoutView(request) :
    if request.user.is_authenticated :
        logout(request)
    return redirect('home')

templates/student/login.html
{% extends 'personal/main.html' %}
{% load static %}


{% block content %}

    <form action="" method="post" class="login-form">
        {% csrf_token %}
        <table class="login-table">
            <tr>
                <th><label for="username">username</label></th>
                <td><input type="text" name="username" id="username" autofocus></td>
            </tr>
            <tr><td><br></td></tr>
            <tr>
                <th><label for="password">password</label></th>
                <td><input type="password" name="password" id="password"></td>
            </tr>
        </table>

        <button type="submit" class="btn btn-primary sign-in-btn">sign in</button>
    </form>

{% endblock %}

templates/student/register.html
{% extends 'personal/main.html' %}
{% load static %}


{% block content %}

    <form action="" method="post" class="register-form">
        {% csrf_token %}

        <table class="registration-table" cellspacing="10">
            <tr class="table-row">
                <th>
                    <label for="id_enrollment_no">Enrollment no:</label>
                </th>
                <td>
                    <input type="text" name="enrollment_no" maxlength="255" required id="id_enrollment_no">
                </td>
            </tr>
            <tr><td><br></td></tr>
            
            <tr class="table-row">
                <th>
                    <label for="id_username">Username:</label>
                </th>
                <td>
                    <input type="text" name="username" maxlength="150" required id="id_username">
                </td>
                <td>
                    <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
                </td>
            </tr>
            <tr><td><br></td></tr>
            
            <tr class="table-row">
                <th>
                    <label for="id_password1">Password:</label>
                </th>
                <td>
                    <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
                </td>
                <td>
                    <span class="helptext">
                        <ul>
                            <li>Your password can't be too similar to your other personal information.</li>
                            <li>Your password must contain at least 8 characters.</li>
                            <li>Your password can't be a commonly used password.</li>
                            <li>Your password can't be entirely numeric.</li>
                        </ul>
                    </span>
                </td>
            </tr>
            <tr><td><br></td></tr>
            
            <tr class="table-row">
                <th>
                    <label for="id_password2">Password confirmation:</label>
                </th>
                <td>
                    <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
                </td>
                <td>
                    <span class="helptext">Enter the same password as before, for verification.</span>
                </td>
            </tr>
            <tr><td><br></td></tr>
        </table>

        <button type="submit" class="btn btn-primary sign-up-btn">sign up</button>
    </form>

{% endblock %}